// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Item struct {
	Key   *string                `json:"key"`
	Value map[string]interface{} `json:"value"`
}

type SearchFilter struct {
	Property string    `json:"property"`
	Values   []*string `json:"values"`
}

type SearchInput struct {
	Keywords     []*string       `json:"keywords"`
	Filters      []*SearchFilter `json:"filters"`
	Limit        *int            `json:"limit"`
	RelatedKinds []*string       `json:"relatedKinds"`
}

type SearchRelatedResult struct {
	Kind  string  `json:"kind"`
	Count *int    `json:"count"`
	Items []*Item `json:"items"`
}

type SearchResult struct {
	Count   *int                   `json:"count"`
	Items   []*Item                `json:"items"`
	Related []*SearchRelatedResult `json:"related"`
}
